 /*
 * MAIN Generated Driver File
 * 
 * @file main.c
 * 
 * @defgroup main MAIN
 * 
 * @brief This is the generated driver implementation file for the MAIN driver.
 *
 * @version MAIN Driver Version 1.0.0
*/

/*
© [2024] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/
#include "mcc_generated_files/system/system.h"
#include <stdbool.h>

#define START_BYTE          0x0F    /* Start byte used for clock synch - first nibble must be 0*/
#define STOP_BYTE           0xF0    /* Stop byte, last nibble must be 0  */

/*
 * The MSSP1 is used to create the BiPhase stream, the SPI bitrate is the same with
 * BiPhase Encoder rates 
 * The following bitrate are configured - refer to spi1_configuration_name_t in mssp1.h
 * 
    HOST_CONFIG_31k25,
    HOST_CONFIG_125k,
    HOST_CONFIG_250k,
    HOST_CONFIG_62k5,
    HOST_CONFIG_500kHz,
 * For other bitrates, open MCC, configure the MSSP1 then select the desired bitrate in 
 * the  BIPHASE_BAUD_RATE macro  
 */
         
#define BIPHASE_BAUD_RATE   HOST_CONFIG_31k25   /* Biphase communication baud rate */

// define the period between autogenerated messages (BeaconMessage)
#define AUTOFRAME_PERIOD_MS(x)     (x * 5)

static uint8_t BeaconMessage[] = "PIC16F13145 CLB Bi-phase Encoder Example\n\r";

uint8_t FrameBuffer[64];
uint8_t frameWrIndex;
bool newFrame;

void ResetFrame(void)
{
    frameWrIndex = 0;
    newFrame = false;
}

void BiPhaseTransmit(uint8_t bitRate, uint8_t* buffer, uint8_t length)
{
/*
 The BiPhase output is available on pin RB7
 */
    uint8_t commandByte;

    SPI1_Open(bitRate);
    
    commandByte = START_BYTE ;
    SPI1_BufferWrite(&commandByte,1);
    
    SPI1_BufferWrite(buffer, length);
    
    commandByte = STOP_BYTE ;
    SPI1_BufferWrite(&commandByte,1);
    
    SPI1_Close();
}

/*
    Main application
*/

int main(void)
{
    static uint8_t oldByte;
    uint8_t receivedByte;
    uint16_t beaconCnt;     
    
    SYSTEM_Initialize();

    // If using interrupts in PIC18 High/Low Priority Mode you need to enable the Global High and Low Interrupts 
    // If using interrupts in PIC Mid-Range Compatibility Mode you need to enable the Global and Peripheral Interrupts 
    // Use the following macros to: 

    // Enable the Global Interrupts 
    INTERRUPT_GlobalInterruptEnable(); 

    // Disable the Global Interrupts 
    //INTERRUPT_GlobalInterruptDisable(); 

    // Enable the Peripheral Interrupts 
    INTERRUPT_PeripheralInterruptEnable(); 

    // Disable the Peripheral Interrupts 
    //INTERRUPT_PeripheralInterruptDisable(); 

    while (1)
    {
        if(EUSART1_IsRxReady() == true)
        {   
            beaconCnt = 0x00;
            receivedByte = EUSART1_Read();
            
            if ((receivedByte == 0x0A) && ( oldByte == 0x0D))
            {
                newFrame = true;
            }
            FrameBuffer[frameWrIndex++] = receivedByte;
            oldByte = receivedByte;

            if (newFrame == true)
            {
                BiPhaseTransmit(BIPHASE_BAUD_RATE, FrameBuffer, frameWrIndex);
                ResetFrame();
                LED0_Toggle();
            }
            
            if (frameWrIndex > 64) 
            {
                ResetFrame();
            }
        }
        //software delay ~ 200 us
        for (uint8_t i = 0; i < 138; i++);
        beaconCnt++;
        if (beaconCnt >= AUTOFRAME_PERIOD_MS(500) )
        {
            beaconCnt = 0x00;
            BiPhaseTransmit(BIPHASE_BAUD_RATE, BeaconMessage, (sizeof(BeaconMessage)-1));
            LED0_Toggle();
        }        
    }   
}